---
# tasks file for pip (Ubuntu specific)

- name: Install pip packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ pip_packages }}"
  tags:
    - pip
